Repository fjprog102/latamat02, pull requests merged in 2022-12, with the labels that each got.

#162 Create TokyoBoardProcessor; adjust TokyoBoard, Game and GameController classes
  KOF/Game/Models/Elements/TokyoBoard.cs
  KOF/Game/Models/Processors/TokyoBoardProcessor.cs
  KOF/Game/Services/Elements/GameService.cs
  KOF/GameTest/ControllersTest/GameControllerTest.cs
  KOF/GameTest/ModelsTest/Elements/GameTest.cs
  KOF/GameTest/ModelsTest/Elements/TokyoBoardProcessorTest.cs
  KOF/GameTest/ModelsTest/Elements/TokyoBoardTest.cs
Labels: kof, sprint2

#157 Added mongo demo implementation
  KOF/Game/Controllers/Elements/PowerCardController.cs
  KOF/Game/KOF.csproj
  KOF/Game/Models/Elements/PowerCard.cs
  KOF/Game/Models/KOTDatabaseSettings.cs
  KOF/Game/Program.cs
  KOF/Game/Services/Elements/PowerCardService.cs
  KOF/Game/appsettings.json
  KOF/GameTest/ControllersTest/Elements/PowerCardControllerTests.cs
  KOF/GameTest/ModelsTest/Elements/PowerCardTests.cs
  KOF/GameTest/ModelsTest/KOTDataBaseSettingsTests.cs
  KOF/GameTest/ServicesTest/Elements/PowerCardServiceTests.cs
  KOF/README.md
Labels: kof, sprint2

#169 Implementation of Monsters with MongoDB
  KOF/Game/Controllers/Elements/MonsterController.cs
  KOF/Game/Models/Elements/Monster.cs
  KOF/Game/Models/KOTDatabaseSettings.cs
  KOF/Game/Services/Elements/MonsterService.cs
  KOF/Game/appsettings.json
  KOF/GameTest/ModelsTest/Elements/MonsterTest.cs
Labels: kot, sprint2

#170 MongoDB implementations for Game
  KOF/Game/Controllers/Elements/GameControllers.cs
  KOF/Game/Models/Elements/Game.cs
  KOF/Game/Models/KOTDatabaseSettings.cs
  KOF/Game/Services/Elements/GameService.cs
  KOF/Game/appsettings.json
Labels: kot, sprint2

#174 Added mongo driver handler and powercard service tests
  KOF/Game/Models/KOTDatabaseSettings.cs
  KOF/Game/Services/DatabaseService.cs
  KOF/Game/Services/Elements/PowerCardService.cs
  KOF/Game/Services/Interfaces/IDatabaseService.cs
  KOF/Game/Services/Interfaces/IPowerCardService.cs
  KOF/Game/Services/ServiceInjector.cs
  KOF/Game/appsettings.json
  KOF/GameTest/ServicesTest/Elements/PowerCardServiceTests.cs
Labels: kot, sprint2

#184 Added singleton Database service injection to MonsterService
  KOF/Game/Services/Elements/MonsterService.cs
  KOF/GameTest/ServicesTest/Elements/MonsterServiceTest.cs
Labels: kot, sprint2

#172 Create PlayerActions classes, DiceAnalyzer classes and unit tests
  KOF/Game/Controllers/Abstracts/PlayerAction.cs
  KOF/Game/Controllers/Elements/DiceAnalyzer.cs
  KOF/Game/Controllers/PlayerActions/GainEnergyCube.cs
  KOF/Game/Controllers/PlayerActions/GainLifePoints.cs
  KOF/Game/Controllers/PlayerActions/GainVictoryPoints.cs
  KOF/Game/Controllers/PlayerActions/SmashMonsters.cs
  KOF/Game/Models/Elements/Game.cs
  KOF/Game/Models/Elements/Player.cs
  KOF/Game/Models/Payloads/GamePayload.cs
  KOF/Game/Models/Payloads/PlayerPayload.cs
  KOF/Game/Models/Processors/TokyoBoardProcessor.cs
  KOF/Game/Services/Elements/GameService.cs
  KOF/Game/Services/Elements/PlayerService.cs
  KOF/GameTest/ControllersTest/Elements/DiceAnalyzerTest.cs
  KOF/GameTest/ControllersTest/GameControllerTest.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/GainEnergyCubesTest.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/GainLifePointsTest.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/GainVictoryPointsTest.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/SmashMonstersTest.cs
  KOF/GameTest/ModelsTest/Elements/GameTest.cs
  KOF/GameTest/ModelsTest/Elements/TokyoBoardProcessorTest.cs
Labels: kot, sprint2

#187 Implemented hosted database and added all monsters to it
  KOF/Game/appsettings.json
  KOF/README.md
Labels: kot, sprint2

#188 Implement EnterTokyo and StartTurn actions with unit tests; modify attribute name of Game/GamePayload
  KOF/Game/Controllers/PlayerActions/EnterTokyo.cs
  KOF/Game/Controllers/PlayerActions/GainEnergyCube.cs
  KOF/Game/Controllers/PlayerActions/GainLifePoints.cs
  KOF/Game/Controllers/PlayerActions/GainVictoryPoints.cs
  KOF/Game/Controllers/PlayerActions/SmashMonsters.cs
  KOF/Game/Controllers/PlayerActions/StartTurn.cs
  KOF/Game/Models/Elements/Game.cs
  KOF/Game/Models/Payloads/GamePayload.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/EnterTokyoTest.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/GainEnergyCubesTest.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/GainLifePointsTest.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/StartTurnTest.cs
Labels: kot, sprint2

#192 Added singleton db service injection to GameService.cs and implemented Update method
  KOF/Game/Services/DatabaseService.cs
  KOF/Game/Services/Elements/GameService.cs
  KOF/Game/Services/Interfaces/IDatabaseService.cs
  KOF/Game/Services/Interfaces/IGameService.cs
Labels: kot, sprint2

#194 Create Turn class and BuyPowerCard-EndTurn actions with unit tests; adjust Game and EnterTokyo files
  KOF/Game/Controllers/Elements/Turn.cs
  KOF/Game/Controllers/PlayerActions/BuyPowerCard.cs
  KOF/Game/Controllers/PlayerActions/EndTurn.cs
  KOF/Game/Controllers/PlayerActions/EnterTokyo.cs
  KOF/Game/Models/Elements/Game.cs
  KOF/Game/Models/Payloads/GamePayload.cs
  KOF/Game/Services/Elements/GameService.cs
  KOF/GameTest/ControllersTest/Elements/TurnTest.cs
  KOF/GameTest/ControllersTest/GameControllerTest.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/BuyPowerCard.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/EndTurnTest.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/EnterTokyoTest.cs
  KOF/GameTest/ModelsTest/Elements/GameTest.cs
  KOF/GameTest/ServicesTest/Elements/GameServiceTest.cs
Labels: kot, sprint2

#200 Implemented `Update` with generic type for extensibility and refactor `GameService` `Update` method
  KOF/Game/Models/Elements/Player.cs
  KOF/Game/Services/DatabaseService.cs
  KOF/Game/Services/Elements/GameService.cs
  KOF/Game/Services/Interfaces/IDatabaseService.cs
  KOF/GameTest/ServicesTest/Elements/GameServiceTest.cs
Labels: kot, sprint3

#201 Create EliminatePlayer-CheckWinner classes with unit test; adjust gameactions arguments and Turn classes
  KOF/Game/Controllers/Abstracts/GameAction.cs
  KOF/Game/Controllers/Elements/DiceAnalyzer.cs
  KOF/Game/Controllers/Elements/Turn.cs
  KOF/Game/Controllers/GameActions/CheckWinner.cs
  KOF/Game/Controllers/GameActions/EliminatePlayer.cs
  KOF/Game/Controllers/GameActions/PlayerActions/BuyPowerCard.cs
  KOF/Game/Controllers/GameActions/PlayerActions/EndTurn.cs
  KOF/Game/Controllers/GameActions/PlayerActions/EnterTokyo.cs
  KOF/Game/Controllers/GameActions/PlayerActions/GainEnergyCube.cs
  KOF/Game/Controllers/GameActions/PlayerActions/GainLifePoints.cs
  KOF/Game/Controllers/GameActions/PlayerActions/GainVictoryPoints.cs
  KOF/Game/Controllers/GameActions/PlayerActions/SmashMonsters.cs
  KOF/Game/Controllers/GameActions/PlayerActions/StartTurn.cs
  KOF/Game/Controllers/PlayerActions/BuyPowerCard.cs
  KOF/Game/Models/Elements/Game.cs
  KOF/Game/Models/Payloads/GamePayload.cs
  KOF/Game/Services/Elements/GameService.cs
  KOF/GameTest/ControllersTest/Elements/DiceAnalyzerTest.cs
  KOF/GameTest/ControllersTest/Elements/TurnTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/CheckWinnerTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/EliminatePlayerTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/BuyPowerCard.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/EndTurnTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/EnterTokyoTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/GainEnergyCubesTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/GainLifePointsTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/GainVictoryPointsTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/SmashMonstersTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/StartTurnTest.cs
  KOF/GameTest/ControllersTest/GameControllerTest.cs
  KOF/GameTest/ModelsTest/Elements/GameTest.cs
  KOF/GameTest/ServicesTest/Elements/GameServiceTest.cs
Labels: kot, sprint3

#193 Added select dices service
  KOF/Game/Controllers/Elements/Turn.cs
  KOF/Game/Controllers/PlayerActions/SelectDices.cs
  KOF/Game/Models/Abstracts/Dice.cs
  KOF/Game/Models/Elements/KofDice.cs
  KOF/Game/Models/Payloads/ChoosenDicePayload.cs
  KOF/Game/Services/Actions/SelectDiceService.cs
  KOF/Game/Services/Interfaces/ISelectDiceService.cs
  KOF/Game/Services/ServiceInjector.cs
  KOF/GameTest/ControllersTest/PlayerActionsTest/SelectDiceTests.cs
  KOF/GameTest/ModelsTest/Elements/KofDiceTest.cs
  KOF/GameTest/ServicesTest/Actions/SelectDiceServiceTests.cs
Labels: kot, sprint2

#204 Increased Coverage Report adding/improving unit tests
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/GainEnergyCubesTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/GainLifePointsTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/GainVictoryPointsTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/SelectDiceTests.cs
  KOF/GameTest/ModelsTest/Elements/PlayerTest.cs
  KOF/GameTest/ModelsTest/Elements/TokyoBoardProcessorTest.cs
Labels: kot, sprint3

#202 Valeria/face up random power cards
  KOF/Game/Models/Abstracts/Card.cs
  KOF/Game/Models/Elements/PowerCard.cs
  KOF/Game/Models/Processors/Cards/CardsActions.cs
  KOF/Game/Models/Processors/Cards/CreateDeck.cs
  KOF/Game/Models/Processors/Cards/Elements/CardDetails.cs
  KOF/Game/Models/Processors/Cards/Elements/Effect.cs
  KOF/GameTest/ModelsTest/Processors/CardDetailsTest.cs
  KOF/GameTest/ModelsTest/Processors/EffectTest.cs
  KOF/GameTest/ModelsTest/Processors/PowerCardDeckTest.cs
Labels: sprint3

#215 Refactor ExecutePowerCard/Deck/Effect classes and unit tests and implement Deck on Game
  KOF/Game/Controllers/Abstracts/PowerCardAction.cs
  KOF/Game/Controllers/Elements/TurnController.cs
  KOF/Game/Controllers/GameActions/PlayerActions/ExecutePowerCards.cs
  KOF/Game/Controllers/GameActions/PlayerActions/SelectDices.cs
  KOF/Game/Data/Players.json
  KOF/Game/Models/Elements/Game.cs
  KOF/Game/Models/Elements/Player.cs
  KOF/Game/Models/Payloads/GamePayload.cs
  KOF/Game/Models/Payloads/PlayerPayload.cs
  KOF/Game/Models/Processors/Cards/CardsActions.cs
  KOF/Game/Models/Processors/Cards/Elements/Effect.cs
  KOF/Game/Models/Processors/Cards/PowerCardDeck.cs
  KOF/Game/Services/Elements/PlayerService.cs
  KOF/GameTest/ControllersTest/Elements/DiceAnalyzerTest.cs
  KOF/GameTest/ControllersTest/Elements/TurnTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/CheckWinnerTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/EliminatePlayerTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/EndTurnTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/EnterTokyoTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/ExecutePowerCardsTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/GainEnergyCubesTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/GainLifePointsTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/GainVictoryPointsTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/SmashMonstersTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/StartTurnTest.cs
  KOF/GameTest/ControllersTest/PowerCardsActions/ExecutePowerCardsTest.cs
  KOF/GameTest/ModelsTest/Processors/CardDetailsTest.cs
  KOF/GameTest/ModelsTest/Processors/EffectTest.cs
  KOF/GameTest/ModelsTest/Processors/PowerCardDeckTest.cs
Labels: kot, sprint3

#207 Added integration tests for database service
  KOF/Game/Models/KOTDatabaseSettings.cs
  KOF/Game/appsettings.json
  KOF/GameTest/ServicesTest/DatabaseServiceTests.cs
Labels: kot, sprint3

#219 Added Update and Delete method test cases for GameController
  KOF/GameTest/ControllersTest/Elements/GameControllerTest.cs
Labels: kot, sprint3

#218 Added BuyPowerCard implementation and unit test; adjust turn controller and game classes
  KOF/Game/Controllers/Elements/TurnController.cs
  KOF/Game/Controllers/GameActions/CheckWinner.cs
  KOF/Game/Controllers/GameActions/EliminatePlayer.cs
  KOF/Game/Controllers/GameActions/PlayerActions/BuyPowerCard.cs
  KOF/Game/Data/Dices.json
  KOF/Game/Data/Game.json
  KOF/Game/Data/Players.json
  KOF/Game/Models/Elements/Game.cs
  KOF/Game/Services/Elements/GameService.cs
  KOF/GameTest/ControllersTest/Elements/TurnTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/CheckWinnerTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/EliminatePlayerTest.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/BuyPowerCard.cs
  KOF/GameTest/ControllersTest/GameActionsTest/PlayerActionsTest/BuyPowerCardTest.cs
Labels: kot, sprint3

#221 Added PlayerController test cases for UPDATE and DELETE
  KOF/GameTest/ControllersTest/Elements/PlayerControllerTest.cs
Labels: kot, sprint3
